const APP_BASE = 'https://moviebucketapi.herokuapp.com/api';
export const LOGIN = APP_BASE + '/v1/auth/email';
export const REGISTER = APP_BASE + '/v1/register';
export const ACTIVATE = APP_BASE + '/v1/activate';
export const USER_FEED = APP_BASE + '/v1/feeds/user';
export const POSTER_IMAGE_PREFIX = 'https://image.tmdb.org/t/p/w200';
export const BACKDROP_IMAGE_PREFIX = 'https://image.tmdb.org/t/p/w400';
export const BACKDROP_IMAGE_LOWRES = 'https://image.tmdb.org/t/p/w200';
export const MOVIE_DETAILS_URL = 'https://api.themoviedb.org/3/movie';
export const DUMMY_IMAGE_CARD =
  'https://dummyimage.com/150x200/ccc/fff.jpg&text=Not+Available';
export const ACTOR_PROFILE_PATH = 'https://image.tmdb.org/t/p/w200';
export const ACTOR_DETAILS_URL = 'https://api.themoviedb.org/3/person';
export const TRENDING =
  'https://api.themoviedb.org/3/trending/movie/day?api_key=85074de3cb4c16234b82a6e22b5e14e2';
